#add by jiachenghui for support oem trace,2015/05/09
# oem trace

#ifdef CONFIG_OEM_TRACE_SUPORT
obj-$(CONFIG_OEM_TRACE_SUPORT) += oem_trace.o
#endif

#ifdef CONFIG_OEM_FORCE_DUMP
obj-$(CONFIG_OEM_FORCE_DUMP) += oem_force_dump.o
#endif
